### ISSUE TITLE
[KED-2555] Poor Error Message if misspelled/missing parameter is used

### ISSUE THREAD

**Issue by WaylonWalker** [quantumblacklabs/kedro-viz#435]
## Description
Short description of the problem here.

## Context
How has this bug affected you? What were you trying to accomplish?

## Steps to Reproduce

1. Create a new project with `pipx run kedro new`
2. Create a parameter in `parameters.yml`
3. Create a node that uses that parameter
4. Ensure that `kedro viz` does work
5. remove/mispell the parameter in parameters.yml
5. `kedro viz` is now broken

## Expected Result

`kedro viz` should provide an error that is more intuitive and leads the user to knowing that a parameter is misspelled or potentially missing.

### Possible Expectation

```
KedroParameterError: typo is not a valid parameter, see valid parameters with `catalog.list('params')
```

## Actual Result

`kedro viz` gives a very obscure error that is not very intuitive without reading the `server.py` source.

```
~/git/misspelled-params via 🐍 v3.8.8 via ©misspelled-params took 16s
❯ kedro viz
2021-05-04 21:27:49,539 - kedro.framework.session.store - INFO - `read()` not implemented for `BaseSessionStore`. Assuming empty store.
fatal: not a git repository (or any of the parent directories): .git
2021-05-04 21:27:49,620 - kedro.framework.session.session - WARNING - Unable to git describe /home/waylon/git/misspelled-params
/home/waylon/miniconda3/envs/misspelled-params/lib/python3.8/site-packages/kedro/framework/context/context.py:60: DeprecationWarning: Accessing pipelines via the context will be deprecated in Kedro 0.18.0.
  warn(
Traceback (most recent call last):
  File "/home/waylon/miniconda3/envs/misspelled-params/lib/python3.8/site-packages/kedro_viz/server.py", line 755, in viz
    _call_viz(host, port, browser, load_file, save_file, pipeline, env)
  File "/home/waylon/miniconda3/envs/misspelled-params/lib/python3.8/site-packages/kedro_viz/server.py", line 816, in _call_viz
    _DATA = format_pipelines_data(pipelines)
  File "/home/waylon/miniconda3/envs/misspelled-params/lib/python3.8/site-packages/kedro_viz/server.py", line 333, in format_pipelines_data
    format_pipeline_data(
  File "/home/waylon/miniconda3/envs/misspelled-params/lib/python3.8/site-packages/kedro_viz/server.py", line 458, in format_pipeline_data
    _add_parameter_data_to_node(dataset_full_name, task_id)
  File "/home/waylon/miniconda3/envs/misspelled-params/lib/python3.8/site-packages/kedro_viz/server.py", line 542, in _add_parameter_data_to_node
    parameter_value = _get_dataset_data_params(dataset_namespace).load()
AttributeError: 'NoneType' object has no attribute 'load'
kedro.framework.cli.utils.KedroCliError: 'NoneType' object has no attribute 'load'
Run with --verbose to see the full exception
Error: 'NoneType' object has no attribute 'load'

```
## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

I have replicated this issue in this repo [WaylonWalker/kedro-misspelled-params-](https://github.com/WaylonWalker/kedro-misspelled-params-).  You should be able to clone the repo and replicate the error message.

* Kedro-Viz version: 3.10.1 - 3.11.0
* Kedro version used (if relevant): 0.17.2 - 0.17.3
* Python version used (if relevant): 3.8

## Checklist
- [ ] Include labels so that we can categorise your issue

**Comment by limdauto** [comment]
Thank you @WaylonWalker for reporting this issue. Will prioritise fixing it soon.
