### ISSUE TITLE
[KED-2764] pydantic.error_wrappers.ValidationError on PartionedDataSet

### ISSUE THREAD

**Issue by sbrugman** [quantumblacklabs/kedro-viz#501]
## Description
Opening the side panel by clicking on a PartitionedDataSet results in a ValidationError:
<img width="800" alt="screen" src="https://user-images.githubusercontent.com/9756388/125447148-a22d9298-7544-4ebd-871d-b67b54888a00.png">

## Context
Information for the [PartitionedDataSet](https://kedro.readthedocs.io/en/latest/kedro.io.PartitionedDataSet.html) is not shown in the panel, and the error logs are polluted.

## Steps to Reproduce

1. Create a pipeline containing at least one PartitionedDataSet
2. Run ``kedro-viz``
3. Click on the PartitionedDataSet node
4. Observe error in log and terminal, and missing data

## Expected Result
A filled panel as if the dataset wasn't partioned, with a label/tag etc.

## Actual Result
<img width="379" src="https://user-images.githubusercontent.com/9756388/125447479-ce8983c3-6b3c-4d56-ad7e-0fc42cf7ffc2.png">

```
2021-07-13 13:53:39,384 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/.../venv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/.../venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/.../venv/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/.../venv/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/.../venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/.../venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/.../venv/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/.../venv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/.../venv/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/.../venv/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/.../venv/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/.../venv/lib/python3.8/site-packages/fastapi/routing.py", line 225, in app
    response_data = await serialize_response(
  File "/.../venv/lib/python3.8/site-packages/fastapi/routing.py", line 128, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: <unprintable ValidationError object>
```

## Your Environment
Include as many relevant details as possible about the environment you experienced the bug in:

* pydantic==1.8.2
* kedro==0.17.4
* kedro-viz==3.12.1
* python 3.8.2

## Checklist
- [X] Include labels so that we can categorise your issue

**Comment by limdauto** [comment]
Hi @sbrugman thank you for reporting this issue. Will get it fixed in the next release.

**Comment by limdauto** [comment]
This is now fixed and released.
